# Generated by Django 4.2.8 on 2023-12-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_contact_updated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created_date',)},
        ),
    ]
